In [1]:
from sklearn.datasets import fetch_openml

from sklearn.preprocessing import OrdinalEncoder

In [2]:
data = fetch_openml('car' , as_frame = True).frame

d:\ML basics\myenv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

In [3]:
data.head(6)

  buying  maint doors persons lug_boot safety binaryClass
0  vhigh  vhigh     2       2    small    low           P
1  vhigh  vhigh     2       2    small    med           P
2  vhigh  vhigh     2       2    small   high           P
3  vhigh  vhigh     2       2      med    low           P
4  vhigh  vhigh     2       2      med    med           P
5  vhigh  vhigh     2       2      med   high           P

Ordinal Encoding  : Used in cases where there is spectrum like which value is higher or lower. Eg: easy , medium , high (Althoough words they show show form  of quantity so they can be easily numbered on order of smallest to largest or lower to higher etc.)

In [4]:
columns_to_encode = ['lug_boot' , 'safety']

encoder = OrdinalEncoder(
    categories = [['small', 'med' , 'big'] , ['low' , 'med' , 'high']]

)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

In [5]:
data.tail(7)

     buying maint  doors persons  lug_boot  safety binaryClass
1721    low   low  5more    more       0.0     2.0           N
1722    low   low  5more    more       1.0     0.0           P
1723    low   low  5more    more       1.0     1.0           N
1724    low   low  5more    more       1.0     2.0           N
1725    low   low  5more    more       2.0     0.0           P
1726    low   low  5more    more       2.0     1.0           N
1727    low   low  5more    more       2.0     2.0           N

In [6]:
data[columns_to_encode] = encoder.inverse_transform(data[columns_to_encode])

In [7]:
data.tail()

     buying maint  doors persons lug_boot safety binaryClass
1723    low   low  5more    more      med    med           N
1724    low   low  5more    more      med   high           N
1725    low   low  5more    more      big    low           P
1726    low   low  5more    more      big    med           N
1727    low   low  5more    more      big   high           N

One hot encoding : Used when the label value is not explicitly on any spectrum that indicate higher or lower value. Eg : For race we have white, black , brown etc. since there is no progression (higher or lower) shown by the value only .

In [8]:
data = fetch_openml('adult' , as_frame = True).frame

d:\ML basics\myenv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

In [9]:
data.head(4)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
data['occupation'].value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [12]:
for value in data['occupation'].unique():
    print(value)

Adm-clerical
Exec-managerial
Handlers-cleaners
Prof-specialty
Other-service
Sales
Craft-repair
Transport-moving
Farming-fishing
Machine-op-inspct
Tech-support
nan
Protective-serv
Armed-Forces
Priv-house-serv

In [13]:
import pandas as pd

encoder = OneHotEncoder(handle_unknown = 'ignore' , sparse_output = False)

encoded_value  = encoder.fit_transform(data[['occupation', 'race']])

new_column = encoder.get_feature_names_out(['occupation', 'race'])

In [17]:
df_encoded = pd.DataFrame(encoded_value , columns = new_column , index = data.index)

data_final = pd.concat([data.drop(columns = ['occupation' , 'race']) , df_encoded] , axis =1 )

In [ ]:
data_final.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K